flanker/addresslib/validate.py

**Purpose**
Right now, if we fail to connect to a MX server, we cache that as unable to connect. This can cause issues if the inability to connect was either a DNS timeout or some other temporary network issues. This commit changes this behavior to not cache the result of a MX lookup.
**Implementation**
In the function `mail_exchanger_lookup` in `validate.py` remove the lines that cache lookup values that were `False`.

If unable to contact a host, don't cache that result.

---

flanker/addresslib/address.py
tests/addresslib/address_test.py

When decoding, addresslib shouldn't assume strings are only ASCII.
```
>>> from flanker.addresslib import address
>>> address.parse_list([u'A <\xfc@b.com>'])
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Library/Python/2.7/site-packages/flanker/utils.py", line 99, in wrapper
return_value = f(*args, **kwargs)
File "/Library/Python/2.7/site-packages/flanker/addresslib/address.py", line 133, in parse_list
address_list = ', '.join([str(addr) for addr in address_list])
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 3: ordinal not in range(128)
```
Discovered via https://github.com/inboxapp/inbox/issues/102

Fix for decoding errors if the list includes a non-ASCII string.

---

flanker/mime/message/part.py
setup.py
tests/__init__.py
tests/fixtures/messages/bz2-attachment.eml
tests/mime/message/part_test.py

**Purpose**
Some content types are tricky and hard for heuristic based content type discovery algorithms. For example, `bzip2` files typically retain their file extension, and content type discovery algorithms like the one in `mimetypes` mark `bzip2` filenames like `foo.txt.bz2` as `text/plain` because of the `.txt` in the filename.
This commit adds support for overriding the heuristic and for certain tricky filetypes, returning hard-coded values. This specific PR only adds support for `bzip2` and `gzip`
**Implementation**
* If the specific content type was not already discovered and simply marked as `application/octet-stream` then the function `adjust_content_type` in `part.py` first calls the internal  `_guess_type` to see if it can discover the content type based off the filename.
* …

Override tricky content types.

---

flanker/addresslib/plugins/hotmail.py
tests/addresslib/plugins/hotmail_test.py

I have seen @live.com e-mail addresses that are valid beginning with a number. Since live.com's MX record resolves to hotmail, this commit loosens the prefix restriction to allow numbers.

Allow hotmail addresses to begin with a number

---

flanker/addresslib/plugins/gmail.py
flanker/addresslib/validate.py
tests/addresslib/plugins/gmail_test.py

**Purpose**
Ordinarily, mail sent to Gmail addresses is stripped of dot (.) characters by the receiving Gmail mail server before being processed. This means Gmail will accept addresses that are syntactically incorrect according to the [RFC 5322 § 3.4.1](http://tools.ietf.org/html/rfc5322#section-3.4.1).
Flanker handles this by having two endpoints, `addresslib.address.parse()` which is strict-ish RFC grammar and `addresslib.address.validate_address()` which applies the RFC rules but also stricter per ESP custom grammar. This lead to odd behavior when we had the stricter API mark an address like `foo...bar@gmail.com` as valid, but the less strict RFC API mark it as invalid.
This seemed like a reasonable compromise at the time. However, based off user feedback, we have found that is a …

Reject consecutive dots (.) in gmail addresses

---

flanker/addresslib/address.py
tests/addresslib/address_test.py

Added a little snippet (and a test) to deal with issue #78.  By
implementing `__ne__`, `email_address != str` behaves as expected.

fix bug with != operator against a string (#78)

---

flanker/mime/message/headers/headers.py
flanker/mime/message/part.py
setup.py
tests/mime/message/fallback/fallback_test.py
tests/mime/message/headers/headers_test.py
tests/mime/message/scanner_test.py

**Purpose**
We want to avoid re-serializing parsed messages, for two reasons:
1. It's slow. We already have the original text, so if we can output it
as-is we save a bunch of work.
2. It canonicalizes headers. This can break DKIM signatures, which hurts
deliverability.
**Implementation**
This commit does three things:
1. `message.headers["some-header"] = "some value"` now causes a prepend
if "some-header" is not present in the message yet. Prepends are
better than arbitrary insertions, because they do not force us to
re-serialize the rest of the message.
2. `message.headers.add("some-header, "some value")` now causes a
prepend, for the same reason as 1. This previously added the header
at the end of the list instead. I am assuming this behavior change is OK.
3. `message.body = …

work harder to avoid re-serializing headers

---

flanker/mime/message/part.py
tests/__init__.py
tests/fixtures/messages/outlook-express.eml
tests/mime/message/part_test.py

flanker.mime.create.from_string does not fully parse message headers.
Instead, headers are parsed lazily the first time they are accessed. So
even though flanker.mime.create.from_string does not support malformed
headers, this isn't a problem if they are never accessed.
Commits 9c89b875dc0eafc01c7f9725d5db5aff8f798f70 and
cd271929bf831999c40e616da3dfacd3694eae56 caused headers to be accessed
every time a message is serialized. This made it impossible to parse and
then re-serialize a message with broken headers, even though this used
to be possible if the headers were never accessed after parsing.
This commit brings back that option: it is again possible to parse and
then re-serialize a message with broken headers.

fix exception in serialization of messages with malformed headers

---

flanker/mime/create.py
flanker/mime/message/part.py
tests/__init__.py
tests/fixtures/messages/false-multipart.eml
tests/mime/message/create_test.py

I didn't test this well enough yesterday. It turns out that the
attachment was getting created, but its ContentType was overwritten to
message/rfc822. This caused problems elsewhere because the the
attachment we created did not have the structure expected for
message/rfc822.
The fix: Don't let Body override our ContentType declaration.

Fix handling for broken .eml messages.

---

flanker/mime/message/headers/parametrized.py
setup.py
tests/mime/message/headers/parsing_test.py

RFC 1521 does not disallow star characters in the type or subtype of a
Content-Type header.

Allow star characters in the type or subtype of a Content-Type header

---

flanker/mime/message/errors.py
setup.py

**Purpose**
Right now the string representation of a `DecodingError` or `EncodingError` can contain the entire MIME message. For example, [this can happen when converting to UTF-8](https://github.com/mailgun/flanker/blob/1831da20f19186ec248daa4e3c178510c752ce0d/flanker/utils.py#L42). This can cause problems when logging messages.
This PR returns a truncated version of that entire message so that the string representation of an `DecodingError` or `EncodingError` can be logged safely but still allows you to access the entire exception when needed.
**Implementation**
Truncate the message returned to 256 characters in `__str__`.

Return short message when getting string representation errors

---

flanker/mime/message/headers/encodedword.py
setup.py

This fixes an exception where a header contains a character that cannot be converted to ASCII, e.g. 0xea. Python will attempt to unicode strings to ascii before passing them to b64encode (which passes it to the internal C function binascii.b2a_b64). This commit forces encoding of the string as UTF-8, which contains no characters that cannot be encoded.
Solves https://github.com/mailgun/flanker/issues/117

Decode to UTF-8 before logging

---

flanker/mime/message/charsets.py
flanker/utils.py
setup.py

When `_guess_and_convert_with` could not detect encoding of a value string it was generating `DecodingError` exception putting the value to the error message. But in some cases that can result in an exception deep inside the standard python logger implementation due to unicode encoding issue. Besides there is no reasonable cap on the size of the converted value. So it is better not to put it in the error message.

Make DecodingError message safe

---

flanker/mime/message/part.py
tests/__init__.py
tests/fixtures/messages/spam/broken-base64.eml
tests/mime/message/part_test.py

Sometimes base64 encoded part might contain invalid base64 string. Following [robustness principle](https://en.wikipedia.org/wiki/Robustness_principle) flanker should try to recover the part.
The length of base64 encoded string should be divisible by 4 and when it's not the case the data should be recovered in the following way:
- If the reminder is greater than 1 the string should be padded.
- If the reminds equals 1 then the string should be trimmed by 1 character. In this PR the last character gets cropped out.

Recover broken base64 parts

---

.gitignore
flanker/addresslib/address.py
flanker/addresslib/lexer.py
flanker/addresslib/parser.py
flanker/addresslib/validate.py
flanker/mime/message/charsets.py
flanker/mime/message/headers/encoding.py
flanker/mime/message/headers/parsing.py
flanker/mime/message/utils.py
flanker/utils.py
setup.py
tests/addresslib/address_test.py
tests/addresslib/metrics_test.py
tests/addresslib/parser_address_list_test.py
tests/addresslib/parser_mailbox_test.py
tests/addresslib/plugins/aol_test.py
tests/addresslib/plugins/gmail_test.py
tests/addresslib/plugins/google_test.py
tests/addresslib/plugins/hotmail_test.py
tests/addresslib/plugins/icloud_test.py
tests/addresslib/plugins/yahoo_test.py
tests/addresslib/validator_test.py
tests/fixtures/abridged_localpart_invalid.txt
tests/fixtures/mailbox_invalid.txt
tests/fixtures/mailbox_valid.txt
tests/mime/message/headers/encodedword_test.py

This PR adds support for non-ASCII characters in the local and domain parts of email addresses and domain literals for the domain part. It completely rewrites the lexer and parser based on [Ply](https://github.com/dabeaz/ply) and heavily refactors of the address module. The previous lexer module, `tokenizer.py`, is kept because some of the domain specific validations use it. Those should be the subject of a later PR.
As far as I'm aware, the public interfaces in the address module should be unchanged and all the addresses that validated previously should still validate properly.
The only potentially breaking change is that I've removed the relaxed vs. strict parsing of mailing lists. The trade-off for having a more flexible parser is that we can't make as many assumptions about an …

Add support for Unicode strings in email addresses

---

flanker/mime/message/scanner.py
tests/mime/message/create_test.py

This fixes a special case where Google would return a multipart/report message
indicating that a message delivery failed. The automated email response contained
a message/rfc822 part (quoting the original message that failed to send) that
has a multipart/alternative boundary with no boundary header, causing parsing to
fail.
Here is a sample python program that reproduces this bug. To be clear, the portion of this raw message that causes parsing to fail is the following line:
`Content-Type: multipart/alternative; boundary=f403045f50f42690580546f0cb4d`
since it isn't followed by any actual boundary.
```
from flanker import mime
google_delivery_failed = """Delivered-To: pfista@gmail.com
Received: by 10.194.110.130 with SMTP id ia2csp2041405wjb;
Wed, 25 Jan 2017 12:08:18 -0800 (PST) …
```

Ignore malformed multipart/alternative boundaries for multipart/report messages

---

flanker/addresslib/address.py
flanker/addresslib/lexer.py
flanker/addresslib/parser.py
flanker/addresslib/quote.py
setup.py
tests/addresslib/address_test.py
tests/addresslib/parser_address_list_test.py
tests/addresslib/parser_mailbox_test.py

Allow period (aka "full stop") in the display name.
According to RFC 5322:
```
Note: The "period" (or "full stop") character (".") in obs-phrase
is not a form that was allowed in earlier versions of this or any
other specification.  Period (nor any other character from
specials) was not allowed in phrase because it introduced a
parsing difficulty distinguishing between phrases and portions of
an addr-spec (see section 4.4).  It appears here because the
period character is currently used in many messages in the
display-name portion of addresses, especially for initials in
names, and therefore must be interpreted properly.
obs-phrase = word *(word / "." / CFWS)
```
The period in the display name make parsing it much more difficult so there were a few things I had to drop support for to get …

Allow dot/full-stop in display name

---

flanker/addresslib/parser.py
setup.py
tests/addresslib/address_test.py
tests/addresslib/parser_mailbox_test.py

While removing an invalid grammer from the parser (`foo foo@bar.com`) I also removed the name address spec without a display name. This was a mistake since [RFC 5322](https://tools.ietf.org/html/rfc5322#section-3.4) defines name address as `name-addr = [display-name] angle-addr`. This patch makes display name optional again.

Add angle address without a display name

---

flanker/addresslib/address.py
flanker/mime/message/headers/encoding.py
setup.py
tests/addresslib/validator_test.py

Looks like our parser allows unicode domain names that cannot be encoded with *idna* encoding. Here is a stack trace from production:
```
Traceback (most recent call last):
File "/app/src/flanker/flanker/mime/message/headers/encoding.py", line 37, in encode
return encode_unstructured(name, value)
File "/app/src/flanker/flanker/mime/message/headers/encoding.py", line 52, in encode_unstructured
return encode_address_header(name, value)
File "/app/src/flanker/flanker/mime/message/headers/encoding.py", line 65, in encode_address_header
out.append(addr.full_spec().encode('utf-8'))
File "/app/src/flanker/flanker/addresslib/address.py", line 536, in full_spec
ace_hostname = self.hostname.encode('idna')
File "/usr/lib/python2.7/encodings/idna.py", line 164, in encode
result.append(ToASCII(label)) …
```

Workaround idna encoding exception

---

flanker/addresslib/lexer.py
flanker/addresslib/parser.py
setup.py
tests/addresslib/parser_mailbox_test.py
tests/fixtures/mailbox_valid.txt

This PR adds comments support to the most commonly used placed in email addresses. It does not attempt to support comments in every place they are technically allowed (in the middle of dot-atoms, middle of the display name, next to the `@` sign, etc.) since that would could problems for the parser. Still, this should cover the vast majority of addresses with comments we see.

Add support for comments in addresses

---

flanker/addresslib/address.py
setup.py
tests/addresslib/address_test.py
tests/addresslib/external_dataset_test.py
tests/addresslib/parser_address_list_test.py
tests/addresslib/parser_mailbox_test.py

This PR adds a fallback method of parsing addresses which supports a variety of address formats we used to accept. If the address can't be parsed normally and `fallback_last_word` evaluates to true the parser will split the address on spaces and assume the last word is the address. The remaining parts are assumed to be the display name. This works for addresses with missing angle brackets surrounding address spec (`foo foo@bar.com`) and special characters in the display name (`not@valid <foo@bar.com>`) as well as many other cases. The intended formatting of the display name may not be preserved 100% in these cases but since the address isn't RFC compliant anyway there's really no way around it.

Optionally fallback to parsing last word of addresses

---

flanker/addresslib/address.py
setup.py
tests/addresslib/address_test.py
tests/fixtures/mailbox_invalid.txt
tests/fixtures/mailbox_valid.txt

In the world where only a few ESP properly support UTF-8 addresses we need a convenient way to construct pure-ASCII address representation **without display name** where possible.
`ace_address` property was introduced that returns pure-ASCII address representation or raises `ValueError` if that is impossible.
* `display_name` property is now a human readable unicode string even if it was [rfc2047](https://www.ietf.org/rfc/rfc2047.txt) encoded in the original parsed address;
* `ace_display_name` property returns ASCII string that is UTF-8 encoded by [rfc2047](https://www.ietf.org/rfc/rfc2047.txt) if necessary;
* `hostname` property is now a human readable unicode string even if it was punycode encoded in the original parsed address;
* `to_unicode()` and `__unicode__()` functions return …

Normalize unicode representation

---

flanker/addresslib/address.py
setup.py
tests/addresslib/address_test.py

Makes the domain part of email address to be proper unicode even when some a-labels are punycode encoded but not the first one.

Convert partial punycode

---

flanker/addresslib/address.py
setup.py
tests/addresslib/address_test.py

Right now we are smart quoting display names before base64 encoding them. As a result, display names with non-ASCII characters will never be quoted since they encoded versions are always pure ASCII. Most times this is OK but if there are special characters in the display name the quotes are required.

Quote display names before encoding them

---

flanker/addresslib/address.py
setup.py
tests/addresslib/address_test.py
tests/addresslib/parser_address_list_test.py

Make three unrelated changes:
1. Fixes `AttributeError: 'NoneType' object has no attribute '_display_name'` exception when parsing an address that has an invalid IDNA alabel;
2. Enforces AddressList to only contain Address objects;
3. Introduces EmailAddress.ace_hostname property to return pure-ASCII representation of the domain part;

Fixes exception when parsing bad IDNA and more

---

.travis.yml
setup.py

`dnsq` and `redis` were made optional, so that they can be installed only if `validator` feature is required.

Make dnsq optional dependency

---

flanker/addresslib/address.py
setup.py
tests/addresslib/address_test.py

When we parse addresses we need to decode display names before we attempt to unquote them. If we do this in the wrong order the quotes aren't removed and the display name will be quoted twice (or more...).
Before:
```
Python 2.7.6 (default, Feb 21 2017, 11:05:11)
[GCC 6.3.1 20161221 (Red Hat 6.3.1-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from flanker.addresslib.address import parse
>>> parse('"Федот @ Стрелец" <test@example.com>').full_spec()
'=?utf-8?b?ItCk0LXQtNC+0YIgQCDQodGC0YDQtdC70LXRhiI=?= <test@example.com>'
>>> parse('=?utf-8?b?ItCk0LXQtNC+0YIgQCDQodGC0YDQtdC70LXRhiI=?= <test@example.com>')
"\"Федот @ Стрелец\"" <test@example.com>
```
After:
```
Python 2.7.6 (default, Feb 21 2017, 11:05:11)
[GCC 6.3.1 20161221 (Red Hat 6.3.1-1)] on …
```

Decode display names before unquoting them

---

flanker/addresslib/quote.py
setup.py
tests/addresslib/address_test.py
tests/addresslib/quote_test.py

Some email clients will add quotes to display names when they are base64 encoded and also contain special characters. This is causing some unexpected twice-quoted display names (`"\"foo.\""`) for some of our customers. This PR should fix that at least for display names containing periods. The display names should all still parse, possibly using the obsolete phrase syntax.

Don't quote periods in display names

---

.travis.yml
build.sh
flanker/addresslib/address.py
flanker/addresslib/parser.py
flanker/addresslib/quote.py
flanker/addresslib/tokenizer.py
flanker/mime/bounce.py
flanker/mime/message/charsets.py
flanker/mime/message/errors.py
flanker/mime/message/fallback/part.py
flanker/mime/message/headers/encodedword.py
flanker/mime/message/headers/encoding.py
flanker/mime/message/headers/headers.py
flanker/mime/message/headers/parametrized.py
flanker/mime/message/headers/parsing.py
flanker/mime/message/headers/wrappers.py
flanker/mime/message/part.py
flanker/mime/message/scanner.py
flanker/mime/message/threading.py
flanker/mime/message/utils.py
flanker/utils.py
setup.py
tests/__init__.py
tests/fixtures/messages/bounce/office365.eml
tests/mime/bounce_tests.py
tests/mime/message/headers/encodedword_test.py
tests/mime/message/headers/encoding_test.py
tests/mime/message/headers/headers_test.py
tests/mime/message/tokenizer_test.py
tox.ini

Turns out Office365 bounce message lack `Content-Description` header, but `Diagnostic-Code` should be more than enough.
With this PR I start a practice to make the changed code work under Python 3. In fact the majority of changes were made just to make the bounce test run under Python 3, rather than to fix the actual problem. All Python 3 compatible logic is now tested with Travis CI against both python versions (see build.sh for the list of tests run under Python 3). 
Making MIME scanner Python 3 I made it so that in both python versions it operates on `str` type, but the semantic of the type as you know is different. So under Python 2 the parser works on binary data, but in Python 3 on text data. It was easier that way. The main hindrance in making entire MIME parser Python 3 compatible …

Fix bounce detection for office365

---

build.sh
flanker/addresslib/address.py
flanker/addresslib/lexer.py
flanker/addresslib/quote.py
flanker/addresslib/tokenizer.py
tests/__init__.py
tests/addresslib/address_test.py
tests/addresslib/corrector_test.py
tests/addresslib/parser_address_list_test.py
tests/addresslib/parser_mailbox_test.py
tests/addresslib/plugins/aol_test.py
tests/addresslib/plugins/gmail_test.py
tests/addresslib/plugins/google_test.py
tests/addresslib/plugins/hotmail_test.py
tests/addresslib/plugins/icloud_test.py
tests/addresslib/plugins/yahoo_test.py
tox.ini

This PR makes flanker/addresslib Python 3 compatible.
The current functionality when running in Python 2 is not changed. In Python 3 we expect text inputs (str) and all methods that return string types (str/unicode) in Python 2 are returning str unconditionally.
The only problem that I have not yet fixed is that ASCII separator symbols `0x1c, 0x1d, 0x1e, 0x1f` for some reason became allowed in the display name in Python 3.

Make addresslib Python 3 compatible

---

flanker/addresslib/plugins/aol.py
tests/addresslib/validator_test.py

Using new dual pattern support since verizon uses aol mx but not the same patterned rules. Open for review (feedback).

AN-66 - adding dual aol pattern for verizion.net

---

flanker/mime/message/headers/parametrized.py
flanker/mime/message/headers/parsing.py
tests/mime/message/fallback/fallback_test.py
tests/mime/message/part_test.py

Non-ascii param will no longer raise DecodingError, as shown in the
old broken_ctype_test. This bug can be reproduced by sending an
attachment in gmail with non-ascii name.
The bug is fixed by tuning regex. Non-ascii params still have to be
double quoted.

Accept non-ascii attachment name

---

flanker/addresslib/address.py
setup.py
tests/addresslib/validator_test.py

We queue a not insignificant number of messages for domains that do not have a valid TLD. These are mostly typos of common mailbox providers like `user@gmail.con` or `user@gmail`. These addresses are technically valid from a grammer perspective because the domain part is a valid atom or dot atom. This patch should allow us to reject these messages immediately instead of wasting resources trying to deliver them.

Add a TLD check to validate_address

---

flanker/mime/message/headers/encoding.py
flanker/mime/message/headers/parsing.py
setup.py
tests/mime/message/create_test.py
tests/mime/message/headers/encoding_test.py
tests/mime/message/headers/headers_test.py

The following limits were removed:
1. _MAX_HEADER_LENGTH - if a header value exceeded this limit we did not fold the value, but weirdly enough still added it to the mime making it in some cases impossible to parse (e.g. the header line size exceeded _MAX_LINE_LENGTH);
2. _MAX_LINE_LENGTH - the limit was applied *after* a header value was parsed, so resources had already been spent on parsing.

Remove unnecessary parsing limits

---

.travis.yml
CHANGELOG.md
flanker/mime/message/utils.py
setup.py
tests/mime/message/headers/encodedword_test.py

The solution is pretty much ported from #84. Unfortunately due to huge code changes made since #84 had been proposed I could not even cherry pick the solution and asking to rebase a 2 year old PR seemed to be too much.
Besides:
- Added a changelog file... finally
- Cherry pick a test for chinese encoding detection from #112. The fix was already in place.

Make dependency on cchardet optional

---

flanker/_email.py
flanker/addresslib/address.py
flanker/mime/__init__.py
flanker/mime/create.py
flanker/mime/message/fallback/create.py
flanker/mime/message/fallback/part.py
flanker/mime/message/headers/encodedword.py
flanker/mime/message/headers/encoding.py
flanker/mime/message/headers/wrappers.py
flanker/mime/message/part.py
flanker/mime/message/threading.py
flanker/mime/message/utils.py
tests/__init__.py
tests/addresslib/parser_mailbox_test.py
tests/addresslib/parser_test.py
tests/email_test.py
tests/mime/bounce_tests.py
tests/mime/message/create_test.py
tests/mime/message/fallback/fallback_test.py
tests/mime/message/headers/encoding_test.py
tests/mime/message/part_test.py
tests/mime/message/scanner_test.py

Module `_email` is introduced to hide all calls to the standard `email` package in one place. The package behaviour changed considerably between Python 2 and Python 3, and this change is supposed to simplify further work on Python 3 support.
Besides the library now consistently produces all CRLF ended strings, previously it was a mixture of `CRLF` and `LF` depending on whether Flanker native code or the standard `email` package was used to produce a line of code.

Create adaptor module _email for the standard email package

---

flanker/addresslib/plugins/_tokenizer.py
flanker/addresslib/plugins/aol.py
flanker/addresslib/plugins/gmail.py
flanker/addresslib/plugins/google.py
flanker/addresslib/plugins/hotmail.py
flanker/addresslib/plugins/icloud.py
flanker/addresslib/plugins/yahoo.py
setup.py

This change allows Unicode characters to be used in custom grammar checks. I tried to limit the changes by keeping the left-to-right `TokenStream` class and re-using the patterns from the main lexer where possible. This should close a bug where some addresses from `hotmail.fr` and the like dont parse correctly.

Allow Unicode characters in custom grammar checks

---

.gitignore
flanker/addresslib/validate.py
setup.py
tests/addresslib/validator_test.py
tox.ini

The changes made here are dealing with the differences between iteration functions in py3 and py2. Specifically, `dnsq` returns a result of a filter function from its `mx_hosts_for` function. In Python 2 it's a list, but for py3 it's an iterator. Later flanker tries to get a `len` of that list which is impossible with an iterator. So this pull request deals with this by converting iterator to a list. 
Other than that there are some improvements in tests.

Improved py36 support

---

flanker/mime/message/headers/encodedword.py
tests/mime/message/headers/encodedword_test.py

Use charset in case of header decoding

---

.gitignore
CHANGELOG.md
flanker/mime/message/part.py
setup.py
tests/mime/message/headers/part_test.py

To replacing the leading '.' in an quoted-printable encoded mime part to avoid obscure SMTP bug.
* This change incurs an additional memory copy for the mime body. This might be of concern for very large mime bodies. We have the option of scanning the body for leading '.' if none are found we can return the body unmodified. This trades off memory consumption for additional CPU usage per message generated.

PIP-631: printed-quotable encoding should convert lines leading in `.` to `=2E`

---

flanker/addresslib/_parser/parser.py

By default the ply/yacc parser generator runs in debug mode. This
creates a parser.out file in the directory parser.py is located. The
user which runs flanker does not always have access to this directory,
which causes 'permission denied errors.'
See https://github.com/mailgun/flanker/issues/208

Issue #208 -- Disable generating parser.out

---

README.rst

`parse_list` and `validate_list` both need an iterable as their first argument rather than _N_ positional args (as suggested by the examples).

Update README.rst to correct usage examples

---

flanker/mime/message/fallback/part.py
flanker/mime/message/headers/wrappers.py
flanker/mime/message/part.py
tests/__init__.py
tests/fixtures/messages/enclosed-global.eml
tests/mime/message/scanner_test.py

https://tools.ietf.org/html/rfc6532#section-3.7
> This media type provides
functionality similar to the message/rfc822 content type for email
messages with internationalized email headers.  When there is a
need to embed or return such content in another message, there is
generally an option to use this media type and leave the content
unchanged or down-convert the content to message/rfc822.
This will allow us to correctly parse content embedded within `message/global` Content Types. Currently, this will result in an exception with the message `Malformed MIME message`.

Account for message/global enclosed Content Type

---

flanker/addresslib/drivers/redis_driver.py

FIxes:
```
return_value = f(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/flanker/addresslib/address.py", line 322, in validate_address
plugin = plugin_for_esp(exchanger)
File "/usr/local/lib/python3.8/site-packages/flanker/addresslib/validate.py", line 129, in plugin_for_esp
if grammar[0].match(mail_exchanger):
TypeError: cannot use a string pattern on a bytes-like object
```

Decode responses from redis

---

flanker/mime/message/headers/encoding.py

Encoding of the sender header is including encoded-words in the addr-spec. This breaks rfc standards. 
> These are the ONLY locations where an 'encoded-word' may appear.  In
>    particular:
> 
>    + An 'encoded-word' MUST NOT appear in any portion of an 'addr-spec'.
https://tools.ietf.org/html/rfc2047
Add Sender to the list of _ADDRESS_HEADERS so flanker will properly encode the header. 
https://mailgun.atlassian.net/browse/PIP-1217

PIP-1217: properly encode non-ascii sender headers

---

flanker/addresslib/drivers/dns_lookup.py
flanker/addresslib/drivers/redis_driver.py

Improve python 3.10 compatibility

feat(python): update collections import for 3.10
